(() => {
  const KEYS = { users: 'kok-us-users-v1', active: 'kok-us-active-v1', custom: 'kok-us-custom-questions-v1', news: 'kok-us-news-v1', sponsors: 'kok-us-sponsors-v1', visits: 'kok-us-visits-v1' };
  const $ = s => document.querySelector(s); const read = (key, fallback) => JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const achievements = [{id:'first',name:'İlk Doğru',test:u=>u.correct>=1},{id:'streak',name:'Seri Ustası',test:u=>u.maxCombo>=5},{id:'quick',name:'Hızlı Matematikçi',test:u=>u.quickWins>=5},{id:'root',name:'Kök Uzmanı',test:u=>u.rootCorrect>=20},{id:'power',name:'Üs Ustası',test:u=>u.powerCorrect>=20},{id:'champ',name:'Matematik Şampiyonu',test:u=>u.score>=500}];
  const emptyUser = name => ({name,score:0,correct:0,wrong:0,games:0,maxCombo:0,combo:0,quickWins:0,rootCorrect:0,powerCorrect:0,achievements:[]});
  const users = () => read(KEYS.users, []); const getUser = () => users().find(u => u.name === localStorage.getItem(KEYS.active));
  function saveUser(user) { const all=users(), i=all.findIndex(u=>u.name===user.name); if(i<0) all.push(user); else all[i]=user; write(KEYS.users,all); localStorage.setItem(KEYS.active,user.name); }
  function ensureUser() { let user=getUser(); if(user) return user; const name=prompt('Oyuna başlamadan önce kullanıcı adını girin:')?.trim(); if(!name) return null; user=users().find(u=>u.name===name)||emptyUser(name); saveUser(user); return user; }
  function customQuestions(){return read(KEYS.custom,[])} function allQuestions(){return [...window.questionBank,...customQuestions()]}
  function switchView(id) { document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id)); document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('active',x.dataset.view===id)); if(id==='leaderboard')renderLeaderboard();if(id==='achievements')renderAchievements();if(id==='games')renderProfile(); if(id==='admin') $('#adminPassword')?.focus(); if(location.hash!==`#${id}`) history.replaceState(null,'',`#${id}`); window.scrollTo({top:0,behavior:'smooth'}); }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view);const game=e.target.closest('[data-game]');if(game){switchView('games');startGame('ten',game.dataset.game)}});
  function renderProfile(){ const u=getUser(); $('#profileCard').innerHTML=u?`<div><b>${escapeHtml(u.name)}</b><br><small>${u.score} puan · ${u.correct} doğru · En yüksek kombo x${u.maxCombo}</small></div><button class="secondary" id="changeUser">Kullanıcı değiştir</button>`:`<div><b>Oyuncu profili</b><br><small>İlerlemen kullanıcı adıyla bu cihazda saklanır.</small></div><button class="primary" id="createUser">Kullanıcı adı gir</button>`; $('#createUser')?.addEventListener('click',ensureUser); $('#changeUser')?.addEventListener('click',()=>{localStorage.removeItem(KEYS.active);renderProfile()}) }
  function startGame(mode, forcedTopic) { const user=ensureUser(); if(!user)return; const topic=forcedTopic || (Math.random()>.5?'uslu':'koklu'); let pool=allQuestions().filter(q=>q.topic===topic); if(mode==='boss')pool=pool.filter(q=>q.boss); const count=mode==='ten'?10:mode==='mastery'?20:mode==='boss'?5:mode==='quick'?99:15; pool.sort(()=>Math.random()-.5); const state={mode,topic,questions:pool.slice(0,count),index:0,correct:0,timer:null}; if(mode==='quick'){let seconds=60;state.timer=setInterval(()=>{seconds--;const timer=$('#timer');if(timer)timer.textContent=`${seconds} sn`;if(!seconds){clearInterval(state.timer);finishGame(state,user)}},1000)} renderQuestion(state,user); }
  function renderQuestion(state,user){const q=state.questions[state.index]; if(!q)return finishGame(state,user); $('#gameArea').classList.remove('hidden'); $('#gameArea').innerHTML=`<article class="question-card glass"><div class="eyebrow">${state.mode==='quick'?'<span id="timer">60 sn</span> · ':''}${state.index+1}/${state.questions.length===99?'∞':state.questions.length} · ${q.topic==='koklu'?'KÖKLÜ İFADELER':'ÜSLÜ İFADELER'} · ${q.difficulty.toUpperCase()}</div><h2>${q.question}</h2><div class="answers">${q.options.map((o,i)=>`<button class="answer" data-answer="${i}">${'ABCD'[i]}) ${o}</button>`).join('')}</div><div id="feedback" class="hidden"></div></article>`; document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(state,user,q,+b.dataset.answer))); }
  function answer(state,user,q,index){const ok=index===q.correctAnswer; document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true); if(ok){user.correct++;state.correct++;user.combo++;user.maxCombo=Math.max(user.maxCombo,user.combo);if(q.topic==='koklu')user.rootCorrect++;else user.powerCorrect++;let bonus=user.combo>=10?50:user.combo>=5?25:user.combo>=3?10:user.combo>=2?5:0;user.score+=q.points+bonus;if(state.mode==='quick')user.quickWins++;}else{user.wrong++;user.combo=0} saveUser(user); const f=$('#feedback');f.className=`feedback ${ok?'correct':'wrong'}`;f.innerHTML=`<b>${ok?'✅ DOĞRU!':'❌ YANLIŞ!'}</b><p><strong>Doğru cevap:</strong> ${q.options[q.correctAnswer]}</p><p><strong>Kısa açıklama:</strong> ${q.explanation}</p><pre>${q.solution}</pre><button class="primary" id="nextQuestion">Devam Et</button>`;f.classList.remove('hidden');$('#nextQuestion').onclick=()=>{state.index++;renderQuestion(state,user)}; }
  function finishGame(state,user){if(state.timer)clearInterval(state.timer);user.games++;saveUser(user);$('#gameArea').innerHTML=`<article class="question-card glass"><h2>Tur tamamlandı! 🎉</h2><p>${state.correct} doğru cevap verdin. Güncel puanın: <b>${user.score}</b></p><button class="primary" onclick="document.querySelector('[data-mode=ten]').click()">Yeni Tur</button></article>`;renderProfile();renderAchievements()}
  document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>startGame(b.dataset.mode)));
  function renderLeaderboard(){const rows=users().sort((a,b)=>b.score-a.score);$('#leaderboardList').innerHTML=`<div class="leader-row"><b>#</b><b>Kullanıcı</b><b>Puan</b><b>Doğru</b><b>Başarı</b><b>Kombo</b></div>${rows.length?rows.map((u,i)=>`<div class="leader-row"><span>${i+1}</span><b>${escapeHtml(u.name)}</b><span>${u.score}</span><span>${u.correct}</span><span>%${percentage(u)}</span><span>x${u.maxCombo}</span></div>`).join(''):'<p class="admin-item">Henüz kayıtlı oyuncu yok.</p>'}`}
  const percentage=u=>u.correct+u.wrong?Math.round(u.correct/(u.correct+u.wrong)*100):0;
  function renderAchievements(){const u=getUser()||emptyUser('Oyuncu');u.achievements=achievements.filter(a=>a.test(u)).map(a=>a.id);if(getUser())saveUser(u);$('#achievementList').innerHTML=achievements.map(a=>`<article class="glass achievement ${u.achievements.includes(a.id)?'':'locked'}"><b>${u.achievements.includes(a.id)?'✦':'○'} ${a.name}</b><small>${u.achievements.includes(a.id)?'Kazanıldı':'Henüz kilitli'}</small></article>`).join('')}
  function renderAnnouncement(){const a=read(KEYS.news,[]).find(x=>x.active);if(a){const el=$('#announcement');el.innerHTML=`<b>${escapeHtml(a.title)}</b><p>${escapeHtml(a.description)}</p><small>${escapeHtml(a.date)}</small>`;el.classList.remove('hidden')}}
  function adminContent(tab='questions'){const el=$('#adminContent');if(tab==='questions'){const qs=customQuestions();el.innerHTML=`<form id="questionForm" class="admin-form"><label>Konu<select id="qTopic"><option value="uslu">Üslü İfadeler</option><option value="koklu">Köklü İfadeler</option></select></label><label>Zorluk<select id="qDifficulty"><option>orta</option><option>orta-zor</option><option>boss</option></select></label><label class="wide">Soru<textarea id="qQuestion" required></textarea></label><label>Seçenekler (| ile ayır)<input id="qOptions" required placeholder="2√3 | 3√2 | 4√3 | 5√2"></label><label>Doğru cevap (0-3)<input id="qCorrect" type="number" min="0" max="3" required></label><label class="wide">Kısa açıklama<textarea id="qExplanation" required></textarea></label><label class="wide">Çözüm<textarea id="qSolution" required></textarea></label><button class="primary">Soruyu Kaydet</button></form><div class="admin-list">${qs.map(q=>`<div class="admin-item"><b>${escapeHtml(q.question)}</b> <button class="danger" data-delete-question="${q.id}">Sil</button></div>`).join('')||'<p>Eklenmiş soru yok.</p>'}</div>`;$('#questionForm').onsubmit=e=>{e.preventDefault();const o=$('#qOptions').value.split('|').map(x=>x.trim());if(o.length!==4)return alert('Tam olarak dört seçenek girin.');const d=$('#qDifficulty').value;const q={id:'custom-'+Date.now(),topic:$('#qTopic').value,difficulty:d,question:$('#qQuestion').value,options:o,correctAnswer:+$('#qCorrect').value,explanation:$('#qExplanation').value,solution:$('#qSolution').value,points:d==='boss'?50:d==='orta-zor'?20:10,boss:d==='boss'};write(KEYS.custom,[...customQuestions(),q]);adminContent()};document.querySelectorAll('[data-delete-question]').forEach(b=>b.onclick=()=>{write(KEYS.custom,customQuestions().filter(q=>q.id!==b.dataset.deleteQuestion));adminContent()})}
    if(tab==='announcements'){const ns=read(KEYS.news,[]);el.innerHTML=`<form id="newsForm" class="admin-form"><label>Başlık<input id="nTitle" required></label><label>Tarih<input id="nDate" type="date" required></label><label class="wide">Açıklama<textarea id="nDesc" required></textarea></label><label><input id="nActive" type="checkbox" checked> Aktif</label><button class="primary">Duyuru Ekle</button></form><div class="admin-list">${ns.map(n=>`<div class="admin-item"><b>${escapeHtml(n.title)}</b> · ${n.active?'Aktif':'Pasif'} <button class="danger" data-news="${n.id}">Sil</button></div>`).join('')}</div>`;$('#newsForm').onsubmit=e=>{e.preventDefault();write(KEYS.news,[...ns,{id:Date.now(),title:$('#nTitle').value,description:$('#nDesc').value,date:$('#nDate').value,active:$('#nActive').checked}]);renderAnnouncement();adminContent('announcements')};document.querySelectorAll('[data-news]').forEach(b=>b.onclick=()=>{write(KEYS.news,ns.filter(n=>n.id!=b.dataset.news));adminContent('announcements')})}
    if(tab==='sponsors'){const ss=read(KEYS.sponsors,[]);el.innerHTML=`<form id="sponsorForm" class="admin-form"><label>Ad<input id="sName" required></label><label>Bağlantı<input id="sLink" type="url"></label><label>Logo URL<input id="sLogo" type="url"></label><label>Aktif <input id="sActive" type="checkbox" checked></label><label class="wide">Kısa açıklama<textarea id="sDesc"></textarea></label><button class="primary">Sponsor Ekle</button></form><div class="admin-list">${ss.map(s=>`<div class="admin-item"><b>${escapeHtml(s.name)}</b><button class="danger" data-sponsor="${s.id}">Sil</button></div>`).join('')||'<p>Sponsor eklenmedi; sitede sponsor alanı gösterilmez.</p>'}</div>`;$('#sponsorForm').onsubmit=e=>{e.preventDefault();write(KEYS.sponsors,[...ss,{id:Date.now(),name:$('#sName').value,link:$('#sLink').value,logo:$('#sLogo').value,description:$('#sDesc').value,active:$('#sActive').checked}]);adminContent('sponsors')};document.querySelectorAll('[data-sponsor]').forEach(b=>b.onclick=()=>{write(KEYS.sponsors,ss.filter(s=>s.id!=b.dataset.sponsor));adminContent('sponsors')})}
    if(tab==='users'){el.innerHTML=users().map(u=>`<div class="admin-item"><b>${escapeHtml(u.name)}</b> — ${u.score} puan, ${u.correct} doğru, %${percentage(u)}, x${u.maxCombo}</div>`).join('')||'<p>Henüz kullanıcı verisi yok.</p>'}
    if(tab==='stats'){const visits=read(KEYS.visits,[]),now=Date.now(),within=n=>visits.filter(v=>now-v.start<n).length;const ended=visits.filter(v=>v.end);const avg=ended.length?Math.round(ended.reduce((x,v)=>x+v.end-v.start,0)/ended.length/1000):null;el.innerHTML=`<div class="admin-item"><b>Bu tarayıcıdaki gerçek oturum verisi</b><br>Toplam oturum: ${visits.length}<br>Son 24 saat: ${within(864e5)} · Son 7 gün: ${within(6048e5)} · Son 30 gün: ${within(2592e6)}<br>Ortalama sitede kalma: ${avg===null?'Henüz yeterli veri yok':avg+' sn'}<br><small>Farklı cihaz/ziyaretçi ve aktif ziyaretçi verisi, sunucu taraflı anonim analiz altyapısı olmadan gösterilmez.</small></div>`}
  }
  $('#adminLoginForm').onsubmit=async e=>{e.preventDefault();const error=$('#adminError');error.textContent='';try{const r=await fetch('/api/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#adminPassword').value})});if(!r.ok)throw new Error((await r.json()).error);sessionStorage.setItem('admin-token',(await r.json()).token);$('#adminLogin').classList.add('hidden');$('#adminTools').classList.remove('hidden');adminContent()}catch(err){error.textContent=err.message||'Giriş başarısız.'}};
  document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>adminContent(b.dataset.adminTab));
  function visit(){const v=read(KEYS.visits,[]);const entry={start:Date.now()};v.push(entry);write(KEYS.visits,v.slice(-100));addEventListener('pagehide',()=>{entry.end=Date.now();write(KEYS.visits,read(KEYS.visits,[]).map(x=>x.start===entry.start?entry:x))},{once:true})}
  const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); visit();renderAnnouncement();renderProfile();renderAchievements(); const initial=location.hash.slice(1); if(document.getElementById(initial)) switchView(initial);
})();
