name = "akaling"
main = "./dist/worker/index.js"
compatibility_date = "2026-09-22"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "KOKUS_DATA"
id = "c4da64e2f28047809396b80ce49208c8"
